services:
  soularr:
    container_name: soularr
    image: mrusse08/soularr:latest
    env_file:
      - path: ./.env
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /vault:/data
      - /config/homelab/volumes/soularr/config/config.ini:/data/config.ini

networks:
  proxy:
    external: true
