services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    env_file:
      - path: ./.env
    environment:
      - UMASK=002
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /vault:/vault
      - /config/homelab/volumes/radarr/config:/config
      - /config/homelab/volumes/radarr/data:/data

networks:
  proxy:
    external: true
