- type: custom-api
  title: immich
  cache: 1d
  url: http://10.0.0.104:2283/api/server/statistics
  headers:
    x-api-key: ${API_IMMICH}
    Accept: application/json
  template: |
    <div class="immich flex flex-column gap-15">
      {{ range $index, $user := .JSON.Array "usageByUser" }}
      <div class="immich-user">
        <div class="color-primary size-h2">{{ $user.String "userName" }}</div>
        <hr class="margin-bottom-10" />
        <div class="flex justify-between text-center">
          <div>
              <div class="color-highlight size-h3">{{ $user.Int "photos" | formatNumber }}</div>
              <div class="size-h6">photos</div>
          </div>
          <div>
              <div class="color-highlight size-h3">{{ $user.Int "videos" | formatNumber }}</div>
              <div class="size-h6">videos</div>
          </div>
          <div>
              <div class="color-highlight size-h3">{{ div ($user.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
              <div class="size-h6">usage</div>
          </div>
        </div>
      </div>
      {{ end }}
    </div>
