- type: monitor
  cache: 5s
  title: media server
  style: compact
  sites:
    - title: plex
      url: http://10.0.0.110:32400/web
      alt-status-codes:
        - 403
    - title: jellyfin
      url: http://10.0.0.111:8096
      alt-status-codes:
        - 403
