- type: monitor
  cache: 5s
  title: services
  style: compact
  sites:
    - title: immich
      url: http://10.0.0.104:2283
      alt-status-codes:
        - 403
    - title: vaultwarden
      url: http://10.0.0.104:80
      alt-status-codes:
        - 403
    - title: linkwarden
      url: http://10.0.0.104:3000
      alt-status-codes:
        - 403
