- type: custom-api
  title: qbittorrent
  cache: 1h
  url: http://10.0.0.103:8080/api/v2/torrents/info?username=${QBIT_USER}&password=${QBIT_PWD}
  template: |
    <!-- Variables -->
    {{ $torrents := .JSON.Array "" }}
    {{ $torrents_num := len ( $torrents ) }}

    <!-- Get Ratio/Uploaded/Downloaded -->
    {{ $uploaded := 0.0 }}
    {{ $downloaded := 0.0 }}
    {{ range $index, $torrent := $torrents }}
      {{ $uploaded = add $uploaded ($torrent.Float "uploaded") }}
      {{ $downloaded = add $downloaded ($torrent.Float "downloaded") }}
    {{ end }}
    {{ $ratio := mul (div $uploaded $downloaded) 100 | toInt }}
    {{ $uploaded_readable := div $uploaded 1073741824 | toInt | formatNumber }}
    {{ $downloaded_readable := div $downloaded 1073741824 | toInt | formatNumber }}

    <!-- Widget -->
    <div class="qbit-container flex justify-between text-center">
      <div>
        <div class="color-highlight size-h3">
          {{ $torrents_num }}
        </div>
        <div class="size-h6">torrents</div>
      </div>

      <div>
        <div class="color-highlight size-h3">
          0.{{ $ratio }}
        </div>
        <div class="size-h6">ratio</div>
      </div>

      <div>
        <div class="color-highlight size-h3">
          {{ $uploaded_readable }}GB
        </div>
        <div class="size-h6">upload</div>
      </div>

      <div>
        <div class="color-highlight size-h3">
          {{ $downloaded_readable }}GB
        </div>
        <div class="size-h6">download</div>
      </div>
    </div>
