- type: group
  widgets:
    - type: videos
      title: tech
      channels:
        - UCXuqSBlHAE6Xw-yeJA0Tunw
        - UCUUTdohVElFLSP4NBnlPEwA
        - UCgdTVe88YVSrOZ9qKumhULQ
        - UCjSEJkpGbcZhvo0lr-44X_w
      style: vertical-list
    - type: videos
      title: code
      channels:
        - UCo71RUe6DX4w-Vd47rFLXPg
        - UCd3dNckv1Za2coSaHGHl5aA
        - UCVk4b-svNJoeytrrlOixebQ
        - UCUyeluBRhGPCW4rPe_UvBZQ
        - UC8ENHE5xdFSwx71u3fDH5Xw
      style: vertical-list
    - type: videos
      title: music
      channels:
        - UCtWuB1D_E3mcyYThA9iKggQ
        - UChUV1sEC7Qdnm9ZR2dk2APg
        - UC4WB8xA2nKBlaZlsXxeuPIQ
        - UCB0qpLkjzVlVZ4c8nKiCEyw
        - UCTBZoXAEZ7X0fR0QF9gcOFA
        - UCQqC08JWnJGJIgw43XJ0GXw
      style: vertical-list
    - type: twitch-channels
      title: twitch
      channels:
        - ThePrimeagen
        - NeverSink
        - broskifgc
        - Ben_
        - pathofexile
        - m4fgaming
        - XavierDang
        - mistermv
        - Mathil1
