services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget
    restart: unless-stopped
    ports:
      - "6789:6789"
    env_file: .env
    environment:
      - UMASK=002
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
        - /config/homelab/volumes/nzbget/config:/config
        - /vault:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - proxy

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file: .env
    environment:
      - UMASK=002
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
        - /config/homelab/volumes/qbittorrent/config:/config
        - /vault:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - proxy

  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    restart: on-failure:2
    env_file: .qbit_manage.env
    volumes:
      - /config/homelab/volumes/qbit_manage/config:/config:rw
      - /vault/torrents/:/data/torrents:rw
      - /config/homelab/volumes/qbittorrent:/qbittorent:ro
      - /config/homelab/volumes/qbittorrent/config/data/BT_backup:/BT_backup:ro
    networks:
      - proxy

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    env_file: .gluetun.env
    volumes:
      - /config/homelab/volumes/gluetun/config:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy

  slskd:
    container_name: slskd
    image: slskd/slskd
    restart: unless-stopped
    env_file: .slskd.env
    network_mode: "service:gluetun"
    volumes:
      - /config/homelab/volumes/slskd/slskd.yml:/app/slskd.yml
      - /vault:/data

  soularr:
    container_name: soularr
    image: mrusse08/soularr:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - SCRIPT_INTERVAL=3600
    volumes:
      - /vault:/data
      - /config/homelab/volumes/soularr/config/config.ini:/data/config.ini
    networks:
      - proxy

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    env_file: .env
    environment:
      - UMASK=002
    volumes:
      - /config/homelab/volumes/prowlarr/config:/config
    networks:
      - proxy

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    env_file: .env
    environment:
      - UMASK=002
    volumes:
      - /vault:/data
      - /config/homelab/volumes/sonarr/config:/config
    networks:
      - proxy

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    env_file: .env
    environment:
      - UMASK=002
    volumes:
      - /vault:/data
      - /config/homelab/volumes/radarr/config:/config
    networks:
      - proxy

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    env_file: .env
    environment:
      - UMASK=002
    volumes:
      - /vault:/data
      - /config/homelab/volumes/lidarr/config:/config
    networks:
      - proxy

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    env_file: .env
    environment:
      - UMASK=002
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - /config/homelab/volumes/bazarr/config:/config
      - /vault:/data
    networks:
      - proxy

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    env_file: .env
    environment:
      - UMASK=002
    volumes:
      - /config/homelab/volumes/jellyseerr/config:/config
    networks:
      - proxy

  defaulterr:
    container_name: defaulterr
    image: varthe/defaulterr:latest
    restart: unless-stopped
    ports:
      - "3184:3184"
    env_file: .env
    environment:
      - LOG_LEVEL=info
    volumes:
      - /config/homelab/volumes/defaulterr/config:/config
      - /config/homelab/volumes/defaulterr/logs:/logs
    networks:
      - proxy

  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - "5454:5454"
    env_file: .env
    volumes:
      - /config/homelab/volumes/notifiarr/config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    networks:
      - proxy

  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    env_file: .env
    volumes:
      - /config/homelab/volumes/tautulli/config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
