vars:
  docker_gpg_url: "https://download.docker.com/linux/debian/gpg"
  docker_apt_repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable"
  docker_daemon_options:
    storage-driver: "overlay2"

tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
      changed_when: false

  - name: Install required packages
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
      state: present

  - name: Create /etc/apt/keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download Docker GPG key
    ansible.builtin.get_url:
      url: "{{ docker_gpg_url }}"
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Add Docker APT repository
    ansible.builtin.apt_repository:
      repo: "{{ docker_apt_repo }}"
      state: present
      filename: docker

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
    changed_when: false

  - name: Install Docker
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  - name: Configure Docker daemon
    template:
      src: "templates/docker_daemon.yml.j2"
      dest: "/etc/docker/daemon.json"
      owner: 'root'
      group: 'root'
      mode: '0755'
    notify: Restart Docker

  - name: Enable Docker
    systemd:
      name: docker
      enabled: true
      state: started

handlers:
  - name: Restart Docker
    ansible.builtin.systemd:
      name: docker
      state: restarted

