services:
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    env_file:
      - path: ./.env
    environment:
      - UMASK=002
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - /config/homelab/volumes/jellyseerr/config:/config

networks:
  proxy:
    external: true
