services:
  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr
    env_file:
      - path: ./.env
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "5454:5454"
    volumes:
      - /config/homelab/volumes/notifiarr/config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id

networks:
  proxy:
    external: true
