services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /config/homelab/volumes/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/titem/certs/:/app/data/docker-tls
    ports:
      - 3001:3001
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
