services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    hostname: cloudflared
    env_file: .env
    command: 'tunnel --no-autoupdate run' # 'tunnel --config /etc/tunnel/config.yml run' 
    volumes:
      - /config/homelab/volumes/cloudflared/:/etc/cloudflared/
    networks:
      - proxy

networks:
  proxy:
    external: true

