services:
  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli
    env_file:
      - path: ./.env
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - /config/homelab/volumes/tautulli/config:/config

networks:
  proxy:
    external: true
