services:
  nzbget:
    image: ghcr.io/hotio/nzbget:release-24.8
    ports:
      - "5550:6789"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
        - /mnt/yesugen/nzbget/config:/config
        - /mnt/juerbiesu/usenet:/data/usenet
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: "nzbget.titem.top"
        caddy.reverse_proxy: "{{upstreams 5550}}"
        caddy.import: tinyauth_forwarder *

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-5.0.5
    ports:
      - "5551:8080"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - WEBUI_PORTS=5551/tcp,5551/udp
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
        - /mnt/yesugen/qbittorrent/config:/config
        - /mnt/juerbiesu/torrents:/data/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: "qbit.titem.top"
        caddy.reverse_proxy: "{{upstreams 5551}}"
        caddy.import: tinyauth_forwarder *

  qbit_manage:
    image: ghcr.io/stuffanthings/qbit_manage:v4.2.2
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/yesugen/qbit_manage/config:/config
      - /mnt/yesugen/qbittorrent:/qbittorent:ro
      - /mnt/yesugen/qbittorrent/config/data/BT_backup:/BT_backup:ro
      - /mnt/juerbiesu/torrents:/data/torrents
    networks:
      - servarr_net

  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "5552:5030"   #slskd
      - "5553:5031"   #slskd
      - "5554:50300" #slksd
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=/var/run/proton-gluetun-private-key
      - SERVER_COUNTRIES=France
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/yesugen/gluetun/config:/gluetun
    secrets:
      - proton-gluetun-private-key
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: slskd.titem.top
        caddy.reverse_proxy: "{{upstreams 5553}}"
        caddy.import: tinyauth_forwarder *

  slskd:
    image: slskd/slskd:0.22.5
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/yesugen/slskd:/app
      - /mnt/juerbiesu/torrents:/data/torrents
    network_mode: "service:gluetun"

  soularr:
    image: mrusse08/soularr:latest
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - SCRIPT_INTERVAL=3600
    volumes:
      - /mnt/yesugen/soularr/config:/data
      - /mnt/juerbiesu/media:/data/media
      - /mnt/juerbiesu/torrents:/data/torrents
    networks:
      - servarr_net

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.35.1.5034
    ports:
      - "5560:9696"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /mnt/yesugen/prowlarr/config:/config
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: prowlarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5560}}"
        caddy.import: tinyauth_forwarder *

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.14.2939
    ports:
      - "5561:8989"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /mnt/yesugen/sonarr/config:/config
      - /mnt/juerbiesu/media:/data/media
      - /mnt/juerbiesu/torrents:/data/torrents
      - /mnt/juerbiesu/usenet:/data/usenet
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: sonarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5561}}"
        caddy.import: tinyauth_forwarder *

  radarr:
    image: ghcr.io/hotio/radarr:release-5.22.4.9896
    ports:
      - "5562:7878"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /mnt/yesugen/radarr/config:/config
      - /mnt/juerbiesu/media:/data/media
      - /mnt/juerbiesu/torrents:/data/torrents
      - /mnt/juerbiesu/usenet:/data/usenet
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: radarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5562}}"
        caddy.import: tinyauth_forwarder *

  lidarr:
    image: ghcr.io/hotio/lidarr:release-2.11.2.4629
    ports:
      - "5563:8686"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /mnt/yesugen/lidarr/config:/config
      - /mnt/juerbiesu/media:/data/media
      - /mnt/juerbiesu/torrents:/data/torrents
      - /mnt/juerbiesu/usenet:/data/usenet
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: lidarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5563}}"
        caddy.import: tinyauth_forwarder *

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.1
    ports:
      - "5564:6767"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - /mnt/yesugen/bazarr/config:/config
      - /mnt/juerbiesu/media:/data/media
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: bazarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5564}}"
        caddy.import: tinyauth_forwarder *

  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:release-2.5.2
    ports:
      - "5570:5055"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /mnt/yesugen/jellyseerr/config:/config
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: jellyseer.titem.top
        caddy.reverse_proxy: "{{upstreams 5570}}"
        caddy.import: tinyauth_forwarder *

  defaulterr:
    image: varthe/defaulterr
    ports:
      - "5580:3184"
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
    volumes:
      - /mnt/yesugen/defaulterr/config:/config
      - /mnt/yesugen/defaulterr/logs:/logs
    networks:
      - servarr_net

  notifiarr:
    image: golift/notifiarr
    ports:
      - "5571:5454"
    volumes:
      - /mnt/yesugen/notifiarr/config:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: notifiarr.titem.top
        caddy.reverse_proxy: "{{upstreams 5571}}"
        caddy.import: tinyauth_forwarder *

  tautulli:
    image: ghcr.io/tautulli/tautulli
    ports:
      - "32401:8181"
    volumes:
      - /mnt/yesugen/tautulli/config:/config
    networks:
      - caddy_net
      - servarr_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        caddy: tautulli.titem.top
        caddy.reverse_proxy: "{{upstreams 32401}}"
        caddy.import: tinyauth_forwarder *

secrets:
  proton-gluetun-private-key:
    external: true

networks:
  caddy_net:
    external: true
  servarr_net:
    driver: overlay
