services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget
    ports:
      - "6789:6789"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=10.0.0.0/24
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_HEALTHCHECK_ENABLED=true
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
        - /config/homelab/volumes/nzbget/config:/config
        - /vault:/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
