services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    user: 1000:1000
    ports:
      - 5432:5432
    environment:
      # So postgres wont do is shitty change of permissions... 
      - PGDATA=/var/lib/postgresql/datadir
    volumes:
      - /data/linkwarden/pgdata:/var/lib/postgresql/datadir
    networks:
      - proxy

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest 
    env_file: .env
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@10.0.0.104:5432/postgres
    volumes:
      - /data/linkwarden:/data/data
    depends_on:
      - postgres

networks:
  proxy:
    external: true
