services:
  glance:
    image: glanceapp/glance:latest
    restart: unless-stopped
    ports:
      - 8081:8080
    secrets:
      - github-token
      - immich-token
      - jellyfin-token
      - plex-token
      - tautulli-token
      - qbit-passwd
    environment:
      TZ: ${TZ}
      IP: ${IP}
      CITY: ${CITY}
      QBIT_USER: ${QBIT_USER}
      PLEX_URL: ${PLEX_URL}
      TAUTULLI_URL: ${TAUTULLI_URL}
      JELLYFIN_URL: ${JELLYFIN_URL}
      JELLYFIN_USER_ID: ${JELLYFIN_USER_ID}
    volumes:
      - /mnt/yesugen/glance/config:/app/config
      - /mnt/yesugen/glance/assets:/app/assets

secrets:
  github-token:
    file: ./secrets/github-token
  immich-token:
    file: ./secrets/immich-token
  jellyfin-token:
    file: ./secrets/jellyfin-token
  plex-token:
    file: ./secrets/plex-token
  tautulli-token:
    file: ./secrets/tautulli-token
  qbit-passwd:
    file: ./secrets/qbit-passwd
