- name: Update repo
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Configure Docker daemon
  template:
    src: "templates/docker_daemon.yml.j2"
    dest: "/etc/docker/daemon.json"
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: Restart Docker

- name: Enable Docker
  systemd:
    name: docker
    enabled: true
    state: started
