services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 80:80
      - 3012:3012 # websocket port
    networks:
      - proxy
    env_file:
      - path: ./.env
    volumes:
      - /data/vaultwarden:/data

networks:
  proxy:
    external: true
