services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    env_file:
      - path: ./.env
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - /vault:/data
      - /config/homelab/volumes/lidarr/config:/config

networks:
  proxy:
    external: true
