services:
  posteria:
    image: bozodev/posteria:latest
    container_name: posteria
    ports:
      - "1818:80"
    env_file: .env
    volumes:
      - /config/homelab/volumes/posteria/data:/var/www/html/data
      - /config/homelab/volumes/posteria/include/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - /config/homelab/volumes/posteria/posters:/var/www/html/posters
      - /config/homelab/volumes/posteria/posters/movies:/var/www/html/posters/movies
      - /config/homelab/volumes/posteria/posters/tv-shows:/var/www/html/posters/tv-shows
      - /config/homelab/volumes/posteria/posters/tv-seasons:/var/www/html/posters/tv-seasons
      - /config/homelab/volumes/posteria/posters/collections:/var/www/html/posters/collections
    restart: unless-stopped
