services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    env_file:
      - path: ./.gluetun.env
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    volumes:
      - /config/homelab/volumes/gluetun/config:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  slskd:
    container_name: slskd
    image: slskd/slskd
    env_file:
      - path: ./.slskd.env
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - /config/homelab/volumes/slskd/slskd.yml:/app/slskd.yml
      - /vault:/data

networks:
  proxy:
    external: true
