services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    env_file:
      - path: ./.env
    environment:
      - UMASK=002
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /config/homelab/volumes/prowlarr/config:/config

networks:
  proxy:
    external: true
