services:
  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    env_file: .env
    volumes:
      - /config/homelab/volumes/qbit_manage/config:/config:rw
      - /vault/torrents/:/data/torrents:rw
      - /config/homelab/volumes/qbittorrent:/qbittorent:ro
      - /config/homelab/volumes/qbittorrent/config/data/BT_backup:/BT_backup:ro
    restart: on-failure:2
    networks:
      - proxy

networks:
  proxy:
    external: true
