all:
  vars:
    ansible_user: 'titem'
    ansible_become: true
    ansible_become_method: sudo
    ansible_private_key_file: /home/titem/.ssh/ansible

debian:
  hosts:
    10.0.0.[20:22]:

docker:
  hosts:
    10.0.0.[20:22]:

gateway:
  hosts:
    10.0.0.20:

traefik_kop:
  hosts:
    10.0.0.[21:22]:

servarr:
  hosts:
    10.0.0.21:

ger:
  hosts:
    10.0.0.22:

