http:
  middlewares:
    bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: # Add LAPI Key
          Enabled: "false"
    tinyauth:
      forwardAuth:
        address: http://tinyauth:3000/api/auth/traefik

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
