- type: releases
  title: neovim
  token: ${TOKEN_GITHUB_RO}
  show-source-icon: true
  repositories:
    - neovim/neovim
    - neovim/nvim-lspconfig
    - folke/lazy.nvim
    - folke/snacks.nvim
    - LazyVim/LazyVim
    - echasnovski/mini.nvim
