- type: releases
  title: servarr
  token: ${TOKEN_GITHUB_RO}
  limit: 20
  show-source-icon: true
  repositories:
    - qdm12/gluetun
    - nzbgetcom/nzbget
    - StuffAnThings/qbit_manage
    - slskd/slskd
    - prowlarr/prowlarr
    - sonarr/sonarr
    - radarr/radarr
    - lidarr/lidarr
    - morpheus65535/bazarr
    - Notifiarr/notifiarr
    - fallenbagel/jellyseerr
    - Tautulli/Tautulli
    - varthe/Defaulterr
