services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    env_file:
      - path: ./.env
    environment:
      - UMASK=002
      - WEBUI_PORTS=6767/tcp,6767/udp
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - /config/homelab/volumes/bazarr/config:/config
      - /vault:/data

networks:
  proxy:
    external: true
